# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rob Forgione
tagline:          'Data Scientist / Analyst / Hacker'
description:      'Data Scientist / Analyst / Hacker. I think deep thoughts. Sometimes I like to write them down.'
#url:              http://rforgione.github.io
#baseurl:          http://rforgione.github.io

author:
  name:           'Mark Otto'
  url:            https://github.com/rforgione

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rforgione.github.io
gems: 	          [jekyll-paginate, jekyll-gist, rb-pygments]
