# Dependencies
highlighter:      rouge
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Rob Forgione
tagline:          'Data scientist and software engineer.'
description:      'Data scientist and software engineer. Currently working on seller marketing tools at <a href="https://etsy.com">Etsy</a>.'
url:              /
# baseurl:          http://rforgione.github.io

author:
  name:           'Rob Forgione'
  url:            https://github.com/rforgione

paginate:         5

github:
  repo:           https://github.com/rforgione/rforgione.github.io
gems: 	          [jekyll-paginate, jekyll-gist, rb-pygments]
