# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rob Forgione
tagline:          'Data scientist and machine learning practitioner.'
description:      'Data scientist and machine learning practitioner. Currently working on optimizing ad products and seller marketing tools at <a href="https://etsy.com">Etsy</a>.'
url:              /
#baseurl:          http://rforgione.github.io

author:
  name:           'Rob Forgione'
  url:            https://github.com/rforgione

paginate:         5

github:
  repo:           https://github.com/rforgione.github.io
gems: 	          [jekyll-paginate, jekyll-gist, rb-pygments]
