# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rob Forgione
tagline:          'Data Scientist / Analyst / Hacker.'
description:      'Data Scientist / Analyst / Hacker. Currently optimizing ad products and seller marketing tools at <a href="https://etsy.com">Etsy</a>.'
url:              /
#baseurl:          http://rforgione.github.io

author:
  name:           'Mark Otto'
  url:            https://github.com/rforgione

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rforgione.github.io
gems: 	          [jekyll-paginate, jekyll-gist, rb-pygments]
