# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rob Forgione
tagline:          'Data Scientist and machine learning practitioner.'
description:      'Data Scientist and machine learning practitioner. Currently helping <a href="https://etsy.com">Etsy</a> optimize its ad products and seller marketing tools.'
url:              /
#baseurl:          http://rforgione.github.io

author:
  name:           'Rob Forgione'
  url:            https://github.com/rforgione

paginate:         5

github:
  repo:           https://github.com/rforgione.github.io
gems: 	          [jekyll-paginate, jekyll-gist, rb-pygments]
