# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Rob Forgione
tagline:          'Data Scientist / Analyst / Hacker'
description:      'I think deep thoughts. Sometimes I like to write them down.'
url:              http://robforgione.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
gems: 	          [jekyll-paginate, jekyll-gist, rb-pygments]
